"""changes on clip model

Revision ID: 61466ff8aa9b
Revises: 037d3b47c853
Create Date: 2025-04-29 17:45:32.710013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61466ff8aa9b'
down_revision: Union[str, None] = '037d3b47c853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clip', sa.Column('content', sa.LargeBinary(), nullable=False))
    op.drop_column('clip', 'filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clip', sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('clip', 'content')
    # ### end Alembic commands ###
