"""user_account to user

Revision ID: f709c2569bae
Revises: 55c9f2b237a2
Create Date: 2025-04-29 12:44:24.780701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f709c2569bae'
down_revision: Union[str, None] = '55c9f2b237a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("action_user_id_fkey", "action", type_="foreignkey")
    op.drop_table("user_account")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_account",
        op.Column("id", sa.Integer, primary_key=True),
        op.Column("email", sa.String(255), unique=True, nullable=False),
        op.Column("password", sa.String(255), nullable=False),
    )
    op.create_foreign_key(
        "action_user_id_fkey", "action", "user_account", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
